In [ ]:
# importing libraries

In [2]:
import requests
import pandas as pd

In [ ]:
# creating a variable for the URL

In [3]:
url = "https://raw.githubusercontent.com/MwangiJoseph-25/api-json-to-dataframe_Project/refs/heads/main/MOCK_DATA.json"

In [ ]:
# Getting a response from the URL

In [4]:
data = requests.get(url)
data.status_code

200

In [ ]:
#getting the data in JSON from the URL and checking data type

In [5]:
data_json = data.json()

In [7]:
type(data_json)

list

In [ ]:
# converting a JSON file into a relational data structure
#slicing the rows to 100

In [9]:
df = pd.DataFrame(data_json[:100])
df

,patient_id,first_name,last_name,gender,dob,blood_type,admission_date,discharge_date,diagnosis,insurance_provider
0,1,Bibbye,Hobell,Female,12/26/2004,O,6/23/2021,8/11/2021,Diabetes,Aetna
1,2,Tiertza,Tomik,Female,5/9/1981,B,6/30/2021,5/12/2021,Cancer,Blue Cross Blue Shield
2,3,Shara,Greening,Female,4/28/1956,A,1/16/2020,9/25/2021,Cancer,Cigna
3,4,Decca,Rowat,Male,12/24/1951,A,4/21/2020,2/18/2020,Pneumonia,Blue Cross Blue Shield
4,5,Antonella,Oselton,Female,3/20/1980,O,8/21/2020,7/18/2020,Diabetes,Blue Cross Blue Shield
...,...,...,...,...,...,...,...,...,...,...
95,96,Wilona,Swarbrigg,Female,7/13/1972,B,4/5/2020,10/2/2021,Diabetes,Blue Cross Blue Shield
96,97,Ruben,Emlin,Male,6/26/1968,AB,7/19/2021,10/20/2020,Pneumonia,Cigna
97,98,Bord,Jentgens,Male,8/26/1958,A,3/31/2021,8/13/2021,Cancer,Aetna
98,99,Esma,Keogh,Female,5/1/1981,A,6/11/2020,7/8/2020,Pneumonia,Aetna
99,100,Lara,Atyeo,Female,4/6/1978,O,7/18/2021,1/3/2020,Diabetes,Blue Cross Blue Shield

In [ ]:
# checking the first 5 rows

In [10]:
df.head()

,patient_id,first_name,last_name,gender,dob,blood_type,admission_date,discharge_date,diagnosis,insurance_provider
0,1,Bibbye,Hobell,Female,12/26/2004,O,6/23/2021,8/11/2021,Diabetes,Aetna
1,2,Tiertza,Tomik,Female,5/9/1981,B,6/30/2021,5/12/2021,Cancer,Blue Cross Blue Shield
2,3,Shara,Greening,Female,4/28/1956,A,1/16/2020,9/25/2021,Cancer,Cigna
3,4,Decca,Rowat,Male,12/24/1951,A,4/21/2020,2/18/2020,Pneumonia,Blue Cross Blue Shield
4,5,Antonella,Oselton,Female,3/20/1980,O,8/21/2020,7/18/2020,Diabetes,Blue Cross Blue Shield

In [ ]:
# converting the data into a CSV file

In [11]:
df.to_csv("Patient_data.csv")